# Generated by Django 4.1 on 2022-12-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0002_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('day1', 'day1'), ('day2', 'day2'), ('day3', 'day3'), ('day4', 'day4'), ('day5', 'day5')], default='day1', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.CreateModel(
            name='Routin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.day_exercise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='exercise',
            field=models.ManyToManyField(to='profile_page.exercise'),
        ),
    ]
