# Generated by Django 4.1 on 2022-12-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0003_day_exercise_remove_exercise_user_routin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
