# Generated by Django 4.1 on 2022-12-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_remove_day_exercise_exercise_day_exercise_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='routin',
            name='name',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day_exercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.exercise'),
        ),
    ]
