# Generated by Django 4.1 on 2022-12-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_routin_name_alter_day_exercise_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='routin',
            name='day',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.routin'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.day_exercise'),
        ),
    ]
