# Generated by Django 4.1 on 2022-12-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0006_remove_day_exercise_exercise_remove_routin_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='day',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='exercises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.exercise'),
        ),
    ]
