# Generated by Django 4.1 on 2022-12-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0007_remove_day_exercise_day_remove_exercise_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_exercise',
            name='rotin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.routin'),
        ),
    ]
