# Generated by Django 4.1 on 2022-12-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0008_day_exercise_rotin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day_exercise',
            old_name='exercises',
            new_name='exercise',
        ),
        migrations.RemoveField(
            model_name='day_exercise',
            name='rotin',
        ),
        migrations.AddField(
            model_name='routin',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.day_exercise'),
        ),
    ]
