# Generated by Django 4.1 on 2022-12-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_rename_exercises_day_exercise_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='routin',
            name='day',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='exercise',
            field=models.ManyToManyField(blank=True, null=True, to='profile_page.exercise'),
        ),
        migrations.AddField(
            model_name='routin',
            name='day',
            field=models.ManyToManyField(blank=True, null=True, to='profile_page.day_exercise'),
        ),
    ]
