# Generated by Django 4.1 on 2022-12-15 09:58

from django.db import migrations, models
import django.db.models.deletion
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0010_remove_day_exercise_exercise_remove_routin_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveField(
            model_name='routin',
            name='date_finish',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=profile_page.models.one_week_hence),
        ),
        migrations.AddField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.todolist'),
        ),
    ]
