# Generated by Django 4.1 on 2022-12-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0014_remove_routin_day_routin_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routin',
            name='day',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='routin',
            field=models.ManyToManyField(blank=True, null=True, to='profile_page.routin'),
        ),
    ]
