# Generated by Django 4.1 on 2022-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0015_remove_routin_day_day_exercise_routin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='routin',
        ),
        migrations.AddField(
            model_name='routin',
            name='day',
            field=models.ManyToManyField(blank=True, null=True, to='profile_page.day_exercise'),
        ),
    ]
