# Generated by Django 4.1 on 2022-12-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0016_remove_day_exercise_routin_routin_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routin',
            name='day',
        ),
        migrations.AddField(
            model_name='routin',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.day_exercise'),
        ),
    ]
