# Generated by Django 4.1 on 2022-12-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0018_remove_routin_day_routin_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='exercise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.exercise'),
        ),
    ]
