# Generated by Django 4.1 on 2022-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0019_remove_day_exercise_exercise_day_exercise_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='exercise',
            field=models.ManyToManyField(blank=True, null=True, to='profile_page.exercise'),
        ),
    ]
