# Generated by Django 4.1 on 2022-12-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0020_remove_day_exercise_exercise_day_exercise_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='routin',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
