# Generated by Django 4.1 on 2023-01-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0022_remove_routin_date_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_exercise',
            name='days',
        ),
        migrations.RemoveField(
            model_name='routin',
            name='day',
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_exercise',
            name='routin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.routin'),
        ),
    ]
